### DISCUSSION TITLE
如何给 Koishi 装两个配置不同的相同插件？

### DISCUSSION THREAD

**Discussion by idlist** [koishijs/koishi#808] [Q&A]
比如我想装两个 novelai，其中一个设置 `model: "furry"`，另一个设置 `allowAnlas: false`，然后两个插件的 `$filter` 不同。

现在的情况是会提示 duplicate plugins detected，然后 context 是对的，但是 config 是两个插件都使用了第一次安装插件时的 config，并不能做到 config 不同 🤔

**Comment by shigma** [comment]
novelai 插件并不支持多次加载 🤔 实际上当多次加载时你也无法保证每次的 filter 是不相交的，如果相交就会冲突。因此这种插件都只有第一次配置生效。目前所有支持重复加载的插件都从逻辑上不会产生上述问题，但 novelai 无法保证。

不过这个问题可以继续讨论。

**Reply by idlist** [reply]
我想的是按注册顺序来，先注册的插件的 context 覆盖后面的 🤔 但不知道好不好做

**Reply by shigma** [reply]
这个不行，因为绝大部分场合下注册顺序都是不确定的。
- 插件可以是异步模块
- 用户可能会更新插件的版本
- 用户可能会修改插件的代码触发重载

**Reply by idlist** [reply]
我有一个这样的东西：

https://github.com/idlist/2bot-v4/blob/66829766420c941ef4e76afc071cc31c596f49e0/wrappers/novelai.js

这样的情况下插件注册的顺序就是确定的了
总之这个需求确实存在 🤔

**Reply by shigma** [reply]
几乎只有在不使用 CLI 的情况下顺序才确定，但我不能抛弃绝大部分用户出一个功能。

需求确实存在的。我想想有没有通用的做法。

**Comment by shigma** [comment]
@idlist 我现在的想法是这样的，搞一个 Computed type，使用上下文选择器选择不同会话下的值。如果写成配置文件就类似于：

```yaml
plugins:
  novelai:
    token: xxx
    allowAnlas: # 动态取值
      - when:
          guild: 12345
        value: true
      - value: false
```

这样做能保证一致性，也能支持序列化。
