### ISSUE TITLE
Bug: koishi 不会做热重载

### ISSUE THREAD

**Issue by mice33** [koishijs/koishi#1026]
### Describe the bug

koishi 不会做热重载

### Steps to reproduce

创建模板项目，再使用 yarn setup 新建插件
使用 yarn dev 启动开发模式
在新建的插件文件中编写保存
koishi 不会做热重载

### Expected behavior

能热重载

### Versions

- Node version: v14.18.3
- Koishi version: 4.12.0

**Comment by Seidko** [comment]
现在热重载已经解耦为 @koishijs/hmr 插件了。

你需要安装 @koishijs/hmr 插件并在 hmr 插件配置中加入你的项目根目录。

**Comment by mice33** [comment]
> 现在热重载已经解耦为 @koishijs/hmr 插件了。
> 
> 你需要安装 @koishijs/hmr 插件并在 hmr 插件配置中加入你的项目根目录。

插件市场里没搜到, 手动 yarn 安装吗

**Comment by shigma** [comment]
最新版的模板项目有点问题。目前你可以采用手动编辑 koishi.yml 的方式解决，把最下面的部分改成这样：

```yaml
  group:develop:
    $if: env.NODE_ENV === 'development'
    hmr:
      root: .
```
