### ISSUE TITLE
Feature: `Schema.dict` 的 i18n 的 yaml 表达

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#1134]
### Describe the problem related to the feature request

i18n

### Describe the solution you'd like

```yaml
dict:
  $key: xxx
  $value: xxx
```
