### ISSUE TITLE
Bug: 在k8s中运行时无法解析域名

### ISSUE THREAD

**Issue by TheresaQWQ** [koishijs/koishi#1162]
### Describe the bug

如题，在k8s中运行时无法解析域名

### Steps to reproduce

在k8s中正常创建一个koishi的，启动后即可看到相关报错

### Expected behavior

正常解析域名

### Screenshots

在容器中使用nslookup可以解析成功
![image](https://github.com/koishijs/koishi/assets/22370654/80a20635-140d-4509-b66a-563986e64498)
koishi无法解析
![image](https://github.com/koishijs/koishi/assets/22370654/789e2a38-7342-4483-b94d-8a84ada8b01c)

### Versions

- OS: Debian12
- Node version: v18.17.0
- Koishi version: v4.14.0

### Additional context

<details><summary>Deployment</summary>
<p>

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: koishi-test
  namespace: iirose
  labels:
    app: koishi-test
  annotations:
    deployment.kubernetes.io/revision: '2'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koishi-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: koishi-test
      annotations:
        kubesphere.io/creator: admin
        kubesphere.io/imagepullsecrets: '{}'
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: koishi-test
          hostPath:
            path: /data/koishi/test
            type: ''
      containers:
        - name: container-rn7th3
          image: 'koishijs/koishi:v1.8.1'
          ports:
            - name: http-0
              containerPort: 5140
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 20m
              memory: 32Mi
          volumeMounts:
            - name: koishi-test
              mountPath: /koishi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

</p>
</details>
