### ISSUE TITLE
Bug: 配置文件中的 `filter` 字段无法使用插值语法

### ISSUE THREAD

**Issue by DreamOfIce** [koishijs/koishi#1170]
### Describe the bug

配置文件中的 `filter` 字段无法使用插值语法，例如：
```yaml
# ……
plugins:
  echo: 
    $filter:
      $ne:
        - $: selfId
        -  ${{ env.FOO }}
# ……
```
此处的插值无法正常工作

### Steps to reproduce

见上

### Expected behavior

在 `filter` 中支持插值语法

### Versions

- OS: Debian 12.1 (Linux 6.3.10-x64v1-xanmod1 #0~20230628.e7ba02f SMP PREEMPT_DYNAMIC Wed Jun 28 23:09:59 UTC  x86_64 GNU/Linux)
- Platform: Villa
- Node version: 18.17.0
- Koishi version: 4.14.1
