### ISSUE TITLE
Bug: 第一个隐式注册的子指令无法继承由`commands`定义的parent authority

### ISSUE THREAD

**Issue by Hieuzest** [koishijs/koishi#1171]
### Describe the bug

（尽管authority已经hidden，但此问题在那之前就已经存在且现在仍然有效）

对于隐式注册的子指令（即没有显示对父指令进行声明的场合），第一个指令的authority不会受到`webui/commands`中定义的authority的影响

### Steps to reproduce

plugin
```
ctx.command('test.foo')
ctx.command('test.bar')
```
koishi.yml
```
...
    commands:
      test:
        config:
          authority: 3
```
此时
test::config.authority = 3
test.foo::config.authority = 1
test.bar::config.authority = 3

### Expected behavior

正常继承

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:
