### ISSUE TITLE
Bug: 无法对 number 类型的配置项进行配置文件插值

### ISSUE THREAD

**Issue by ilharp** [koishijs/koishi#1217]
### Describe the bug

无法对 number 类型的配置项进行配置文件插值，无论是否使用 `Number()`。

### Steps to reproduce

找到任一 number 类型的配置项，如 mysql，并修改为插值：

```yml
plugins:
  group:database:
    database-mysql:
      host: ${{ env.MYSQL_HOST }}
      port: ${{ Number(env.MYSQL_PORT) }}
      password: ${{ env.MYSQL_PASSWORD }}
      database: ${{ env.MYSQL_DATABASE }}
```

### Expected behavior

能够正确读取配置并转换为数字。

### Versions

System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz

Binaries:
    Node: 20.8.0
    Yarn: 1.22.19

Koishi:
    Core: 4.15.0
    Console: 5.15.0

### Additional context

该 bug 分别在 2023 年 4 月 9 日和 2023 年 10 月 11 日遇到。
