### ISSUE TITLE
Bug: 当配置存在 $if 时 在配置页面拖动配置 会报错

### ISSUE THREAD

**Issue by 502647092** [koishijs/koishi#1231]
### Describe the bug

相关配置区域
```
  group:develop:
    $if: env.NODE_ENV === 'development'
    server:tmhcza:
      path: ''
      token: '123456'
    hmr:
      root: .
```

### Steps to reproduce

![f238ad9614234ab3bf45164e084f179d](https://github.com/koishijs/koishi/assets/10203793/77e51c05-7e1b-4ed2-894d-f6312d1c369b)

### Expected behavior

正常处理配置

### Versions

System:
    OS: Linux 3.10 Alpine Linux

Binaries:
    Node: 18.17.1
    Yarn: 3.6.2

Koishi:
    Core: 4.15.1
    Console: 5.16.1
