### ISSUE TITLE
eval-addons: 支持定义 public 字段

### ISSUE THREAD

**Issue by undefined-moe** [koishijs/koishi#124]
支持定义用户直接使用 eval 能 读/写 的字段。

**Comment by Shigma** [comment]
换句话说就是不用声明直接可以用的字段？

**Comment by undefined-moe** [comment]
（指会merge到Eval.Config中的字段）

**Comment by Shigma** [comment]
目前 eval 的 userFields 和 groupFields 是可以直接使用的。你希望它们也合并到 eval-addons 中的 userFields 和 groupFields 去吗？

**Comment by undefined-moe** [comment]
```
version: 1
commands:
  - name: foo
    desc: 一个我也不知道有啥用的指令
    authority: 2
    options:
      - name: bar
    desc: -b <arg> 一个我也不知道有啥用的选项
    userFields:
      - field # 由本扩展定义的字段
    publicUserFields:
      - field # 用户直接使用eval指令也可以获取此字段
```
