### ISSUE TITLE
Feature: `Schema.dict` 的表格形式支持 i18n 的 $value

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#1362]
### Describe the problem related to the feature request

i18n 的 $value 在  `Schema.dict` 的表格形式不生效
```yaml
delay:
  $description: 发送间隔 (默认 100 毫秒)
  $value: 平台名
```
![image](https://github.com/koishijs/koishi/assets/96647698/beba3bab-56d4-494e-8267-a9ba2e92dd03)
显示的是「键」，而不是「平台名」

### Describe the solution you'd like

使 `Schema.dict` 的表格形式支持 i18n 的 $value
