### ISSUE TITLE
[RFC] context selector in config file

### ISSUE THREAD

**Issue by Shigma** [koishijs/koishi#226]
目前我们可以在 Context API 中使用选择器和过滤器（[文档](https://koishi.js.org/guide/context.html)），但并没有一种有效的手段让我们在配置文件中定义插件的上下文。同时，由于配置文件中的插件推荐使用键值对的形式，无法通过简单的方法添加上下文信息。因此在这里需要介绍的内容包含两部分：

1. 如何设计配置文件中的上下文选择器
2. 如何将选择器应用到插件中

预期实装版本：v3.9.0。

## 示例 1

我们采用类似 Selector API 的方法定义选择器，同时相关的属性将加上 `$` 前缀：

```yaml
plugins:
  eval:
    $platform: onebot  # 允许的平台
    $channel:          # 允许的频道名称
      - 123456789
      - 987654321
    root: ../addons    # 其他配置项
    userFields:
      - id
      - authority
```

上面的写法相当于：

```js
app
  .platform('onebot')
  .channel('123456789', '987654321')
  .plugin(require('koishi-plugin-eval'), {
    root: '../addons',
    userFields: ['id', 'authority'],
  })
```

## 示例 2

我们还支持使用 `$union` 实现并集的效果：

```yaml
plugins:
  puppeteer:
    $union:
      - $private: 123456789
      - $group: true
    browser:
      defaultViewport:
        width: 1600
        height: 900
```

上面的写法相当于：

```js
app
  .private('123456789')
  .union(app.group())
  .plugin(require('koishi-plugin-puppeteer'), {
    browser: {
      defaultViewport: {
        width: 1600,
        height: 900,
      },
    },
  })
```

## 支持的关键字

- $user
- $group
- $channel
- $platform
- $self
- $private
- $union
- $exclude

当遇到不支持的关键字时会产生 warning。
