### ISSUE TITLE
Suggestion: Webpack for plugin development

### ISSUE THREAD

**Issue by purerosefallen** [koishijs/koishi#260]
**Is your feature request related to a problem? Please describe.**

When deploying Koishi.js using Docker container, we may want to upload several plugins to the server, and mount them using `volume` into the container.
However, those plugins may depend on other npm packages, resulting in `npm` must be installed on the server, which makes the server environment dirty.
Take the below `docker-compose` file as an example.

```yaml
version: '2.4'
services:
 mysql:
    restart: always
    image: mariadb:10
    volumes:
      - './db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: db_rootpass
      MYSQL_DATABASE: yuzudice
      MYSQL_USER: yuzudice
      MYSQL_PASSWORD: db_pass
  cqhttp:
    restart: always
    image: git-registry.mycard.moe/nanahira/docker-mirai-cqhttp:novnc
    ports:
      - 11180:8080
    volumes:
      - ./cqhttp/data:/usr/src/app/data
      - ./cqhttp/config:/usr/src/app/config
      - ./cqhttp/bots:/usr/src/app/bots
    environment:
      QQ_ID: 11111111
      QQ_PASS: qq_pass
      WS_TOKEN: cq_token
      VNC_PASS: vnc_pass
  koishijs:
    restart: always
    image: koishijs/koishi:latest
    volumes:
      - ./koishi.config.js
      - ./plugins:/usr/src/plugins:ro
```

What should be placed in `plugins` directory?

* A single `js` or `ts` file? We may wish to add other npm packages..
* An entire npm package directory? Also no, unless the server has `npm` already installed.

**Describe the solution you'd like**

In plugin development, use `webpack` to compile into a single js file.
I would send a pull request to one of the plugins for an example later.

**Describe alternatives you've considered**

Something like, auto-perform an `npm install` or `npm ci` when Koishi.js launches? I don't know.

**Additional context**
