### ISSUE TITLE
BUG: Official Docker image failed to start

### ISSUE THREAD

**Issue by purerosefallen** [koishijs/koishi#261]
**Describe the bug**

As the title says.

```
➜  nginx docker-compose logs -f koishijs
Attaching to nginx_koishijs_1
koishijs_1               | [E] app Error: cannot resolve adapter onebot
koishijs_1               |         at loadEcosystem (/app/node_modules/koishi/lib/worker.js:100:9)
koishijs_1               |         at loadAdapter (/app/node_modules/koishi/lib/worker.js:139:3)
koishijs_1               |         at Array.forEach (<anonymous>)
koishijs_1               |         at Object.<anonymous> (/app/node_modules/koishi/lib/worker.js:144:15)
koishijs_1               |         at Module._compile (internal/modules/cjs/loader.js:1063:30)
koishijs_1               |         at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
koishijs_1               |         at Module.load (internal/modules/cjs/loader.js:928:32)
koishijs_1               |         at Function.Module._load (internal/modules/cjs/loader.js:769:14)
koishijs_1               |         at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
koishijs_1               |         at internal/main/run_main_module.js:17:47
koishijs_1               | [E] app Error: cannot resolve adapter onebot
koishijs_1               |         at loadEcosystem (/app/node_modules/koishi/lib/worker.js:100:9)
koishijs_1               |         at loadAdapter (/app/node_modules/koishi/lib/worker.js:139:3)
koishijs_1               |         at Array.forEach (<anonymous>)
koishijs_1               |         at Object.<anonymous> (/app/node_modules/koishi/lib/worker.js:144:15)
koishijs_1               |         at Module._compile (internal/modules/cjs/loader.js:1063:30)
koishijs_1               |         at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
koishijs_1               |         at Module.load (internal/modules/cjs/loader.js:928:32)
koishijs_1               |         at Function.Module._load (internal/modules/cjs/loader.js:769:14)
koishijs_1               |         at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
koishijs_1               |         at internal/main/run_main_module.js:17:47
```

**To Reproduce**

`docker-compose.yml`
```yaml
version: '2.4'
services:
  cqhttp:
    restart: always
    image: git-registry.mycard.moe/nanahira/docker-mirai-cqhttp:novnc
    volumes:
      - ./cq/data:/usr/src/app/data
      - ./cq/config:/usr/src/app/config
      - ./cq/bots:/usr/src/app/bots
    ports:
      - 44481:8080
    environment:
      QQ_ID: 11111111
      QQ_PASS: bbbbbbb
      WS_TOKEN: aaaaaaaaaa
      WS_PORT: 80
      VNC_PASS: ccccccc
  koishijs:
    restart: always
    image: koishijs/koishi
    volumes:
      - ./koishi-plugins:/plugins:ro
      - ./koishi.config.js:/app/koishi.config.js:ro
```

`koishi.config.js`
```js
module.exports = {
  bots: [{
    type: 'onebot:ws',
    server: 'ws://server',
    selfId: 11111111,
    token: 'aaaaaaaaaa',
  }],
  plugins: {
    // some plugins
  },
}
```

**Expected behavior**

It should start..

**Screenshots**

**Versions**

- OS: Debian buster
- Node Version: Just as in docker image
- CoolQ Version: also docker image
- CQHTTP Version: also docker image+1
- Koishi Version: 3.10.1

**Additional context**
