### ISSUE TITLE
Feature: help 指令支持插件内的插值语法

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/koishi#845]
### Describe the problem related to the feature request

我做了一个放大图片的插件 extra，它有一些放大模型可供选择，这些模型不是固定的数量或名称，
希望实现用户在使用 `help extra` 的时候能够获取到可用的模型列表。

### Describe the solution you'd like

希望执行 help 命令时能支持插件 `ctx.option` 或 `ctx.i18n` 中的插值语法~

**Comment by shigma** [comment]
我能想到的一种思路是在 command 和 option 上提供额外的参数 params：

```ts
ctx.command('test', { params: { foo: 1 } })
  .option('alpha', { params: { bar: 2 } })
```

```yaml
commands:
  test:
    description: 测试指令{foo}
    options:
      alpha: 选项{bar}
```

```
help test
测试指令1
可用选项列表：
  --alpha 选项2
```

不知道这种设计能否满足你的需求？
