### ISSUE TITLE
Bug: respondent插件 正则、换行等无法正常使用，并且网页控制台无法配置

### ISSUE THREAD

**Issue by vlssu** [koishijs/koishi#882]
### Describe the bug

@koishijs/plugin-respondent 插件，在 koishi 4.10.6 版本中 正则匹配失效，不识别。
回复的消息的 `\n` 换行也无效，包括直接在配置文件中换行

并且网页控制台无法配置

### Steps to reproduce

```
  respondent:
    rules:
      - match: 菜单
        reply: >-
          ↓↓↓菜单↓↓↓
          卫星地图
          服务器
      - match: /^(.*?)版本(.*?)$/
        reply: 生存服\n空岛服\nOLD生存服
      - match: /^\s*(\S +){2,}\S\s*$/
        reply: 空格警察，出动！
      - match: /^(.+)一时爽$/
        reply: (_, str) => `一直${str}一直爽`
```

### Expected behavior

正则、换行等应正常识别
并且网页控制台可以可视化配置

### Screenshots

![image](https://user-images.githubusercontent.com/43847794/207814309-c52a7609-9091-4dac-85a8-38e825041c93.png)
```
2022-12-15 16:48:50 [D] message [群] 飒爽师叔: 菜单
2022-12-15 16:48:50 [D] gocqhttp 发送群 群(11111111) 的消息: [{"type":" ... (-1397753843)
```

### Versions

- OS:  alpine
- Platform:  QQ
- Node version:  18.12.1
- Koishi version:  4.10.6

https://hub.docker.com/layers/koishijs/koishi/latest-puppeteer/images/sha256-70e04b5b06714d0ec674a25a0deb3d2030ec0ed62e3af63ef512c8f72d40d56c?context=explore

**Comment by shigma** [comment]
你的问题其实是 YAML 语法的问题。请参考下面的代码进行修改。

- 关于正则：在 YAML 中这样写只会解析为字符串。你可以使用 4.10.6 最新的特性来写正则表达式。
- 关于换行：在 YAML 中换行请使用 `|-` 而不是 `>-` (`>` 的作用是去除换行)，或使用 `"生存服\n空岛服"` 而不是 `生存服\n空岛服` 或 `'生存服\n空岛服'` (只能是双引号)

```yaml
  respondent:
    rules:
      - match: 菜单
        reply: |-
          ↓↓↓菜单↓↓↓
          卫星地图
          服务器
      - match: ${{ /^(.*?)版本(.*?)$/ }}
        reply: 生存服\n空岛服\nOLD生存服
      - match: ${{ /^\s*(\S +){2,}\S\s*$/ }}
        reply: 空格警察，出动！
      - match: ${{ /^(.+)一时爽$/ }}
        reply: (_, str) => `一直${str}一直爽`
```

网页控制台无法配置：这是已知问题，未来会解决。
